config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tweets#home"
  devise_for :users
  
  post '/:id/follow', to: "friends#follow", as: "follow"
  post '/:id/unfollow', to: "friends#unfollow", as: "unfollow"
  
  resources :tweets, except: [:edit, :update] do
    resources :likes, only: [:create, :destroy]
  end
  
  get '/home', to: "tweets#home", as: "home"
  
  get '/api/news', to: "api#news"
  get '/api/:start/:final', to: "api#between_dates"
  get '/api/create', to: "api#create"

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  TIME_ZONE = "Santiago"
  validates :content, presence: true, length: {maximum: 280}

  # user reference
  belongs_to :user

  # recursive reference for retweet
  belongs_to :source, class_name: "Tweet", optional: true
  has_many :retweets, class_name: "Tweet", foreign_key: "retweet_id", dependent: :destroy

  # likes model association
  has_many :likes, dependent: :destroy

  # SCOPES
  scope :tweets_for_me, -> (ff) { where(:user_id =>  ff)}
  
  def time_since_publish
    start_date = self.created_at.in_time_zone(TIME_ZONE)
    time_now = Time.now.in_time_zone(TIME_ZONE)

    t = time_now - start_date

    if t < 59.minutes
      mins = (t / 1.minute).round
      mins == 1 ? "#{mins} minuto" : "#{mins} minutos"
    else
      hours = (t / 1.hour).round
      hours == 1 ? "#{hours} hora" : "#{hours} horas"
    end
  end

  def self.search(search)
    if search
      where('lower(content) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[ show update destroy ]
  before_action :is_author?, only: %i[ destroy ]
  before_action :followed_users_ids, only: %i[ profile ]

  TWEETS_PER_PAGE = 50

  # GET /tweets or /tweets.json
  def index
    @search = Tweet.search(params[:query])

    @page = params.fetch(:page, 0).to_i
    @pages = (@search.count / TWEETS_PER_PAGE.to_f).ceil
    
    @tweets = Tweet.search(params[:query]).offset(@page * TWEETS_PER_PAGE).limit(TWEETS_PER_PAGE)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    if not params[:retweet_id].nil?
      @tweet = Tweet.new(retweet_id: params[:retweet_id])
    else
      @tweet = Tweet.new
    end
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    
    if @tweet.save
      redirect_to root_path, notice: "Tweet was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_back(fallback_location: root_path)
  end

  def home
    @page = params.fetch(:page, 0).to_i
    @pages = (followed_users_ids.count / TWEETS_PER_PAGE.to_f).ceil

    @for_user_tweets = Tweet.tweets_for_me(followed_users_ids).offset(@page * TWEETS_PER_PAGE).limit(TWEETS_PER_PAGE)
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :retweet_id).merge(user: current_user)
    end

    def is_author?
      redirect_back(fallback_location: root_path) unless @tweet.user == current_user
    end

    def followed_users_ids
      ids = [current_user.id]
      current_user.followed_users.each do |user|
        ids.append(user.id)
      end

      return ids
    end
    
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def hashtag_render(content)
     content.gsub(/#\w+/){|word| link_to word, "/tweets?query=#{word.delete('#')}", class: "font-medium"}.html_safe
  end
  
end

app/views/tweets/sidebar/_sidebar.html.erb
<%# action buttons %>
<div class="flex space-y-12 mb-14">
    <div class="flex flex-col ml-5 mr-8 space-y-1">

        <%# Only tweets from users followed accounts %>
        <div class="flex">
            <%= link_to home_path do %>
                <div class="button-action-side">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                    </svg>
                    <span class="text-xl select-none">Inicio</span>
                </div>
            <% end %>
        </div>
        
        <%# Explore all tweets button %>
        <div class="flex"> 
            <%= link_to tweets_path do %>
                <div class="button-action-side">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 20l4-16m2 16l4-16M6 9h14M4 15h14" />
                    </svg>
                    <span class="text-xl select-none">Explorar</span>
                </div>
            <% end %>
        </div>

    </div>
    
</div>

<%# new tweet %>
<div class="mr-8">
    <%= link_to new_tweet_path do %>
        <div class="block transition delay-75 ease-in-out bg-blue-500 hover:bg-blue-600 text-center py-3 rounded-full text-white shadow-lg font-bold">Tuittear</div>    
    <% end %>
</div>

<%# current user component %>
<div class="flex flex-row mt-10 rounded-full bg-gray-100 hover:bg-gray-300 justify-between transition delay-75 ease-in-out">
    
    <div class="flex flex-row text-left my-auto">
        <div class="flex flex-col">
            <span class="my-auto mx-5 text-sm font-medium text-gray-500 hover:text-black"><%= link_to "Salir", destroy_user_session_path, method: :delete %></span>
        </div>
        <div class="flex flex-col">
            <span class="font-bold">@<%= current_user.account %></span>
            <span class="text-xs"><%= current_user.email %></span>
        </div>
    </div>

    <%= link_to edit_user_registration_path do %>
        <div class="bg-cover bg-center rounded-full h-12 w-12 m-2 transition delay-75 ease-in-out hover:shadow-lg" style="background-image: url(<%= user.profile_picture %>)"></div>
    <% end %>
    
</div>