config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tweets#home"
  devise_for :users
  
  post '/:id/follow', to: "friends#follow", as: "follow"
  post '/:id/unfollow', to: "friends#unfollow", as: "unfollow"
  
  resources :tweets, except: [:edit, :update] do
    resources :likes, only: [:create, :destroy]
  end
  
  get '/home', to: "tweets#home", as: "home"
  
  get '/api/news', to: "api#news"
  get '/api/:start/:final', to: "api#between_dates"
  get '/api/create', to: "api#create"

end

app/models/tweet.rb
class Tweet < ApplicationRecord
  TIME_ZONE = "Santiago"
  validates :content, presence: true, length: {maximum: 280}

  # user reference
  belongs_to :user

  # recursive reference for retweet
  belongs_to :source, class_name: "Tweet", optional: true
  has_many :retweets, class_name: "Tweet", foreign_key: "retweet_id", dependent: :destroy

  # likes model association
  has_many :likes, dependent: :destroy

  # SCOPES
  scope :tweets_for_me, -> (ff) { where(:user_id =>  ff)}
  
  def time_since_publish
    start_date = self.created_at.in_time_zone(TIME_ZONE)
    time_now = Time.now.in_time_zone(TIME_ZONE)

    t = time_now - start_date

    if t < 59.minutes
      mins = (t / 1.minute).round
      mins == 1 ? "#{mins} minuto" : "#{mins} minutos"
    else
      hours = (t / 1.hour).round
      hours == 1 ? "#{hours} hora" : "#{hours} horas"
    end
  end

  def self.search(search)
    if search
      where('lower(content) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[ show update destroy ]
  before_action :is_author?, only: %i[ destroy ]
  before_action :followed_users_ids, only: %i[ profile ]

  TWEETS_PER_PAGE = 50

  # GET /tweets or /tweets.json
  def index
    @search = Tweet.search(params[:query])

    @page = params.fetch(:page, 0).to_i
    @pages = (@search.count / TWEETS_PER_PAGE.to_f).ceil
    
    @tweets = Tweet.search(params[:query]).offset(@page * TWEETS_PER_PAGE).limit(TWEETS_PER_PAGE)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    if not params[:retweet_id].nil?
      @tweet = Tweet.new(retweet_id: params[:retweet_id])
    else
      @tweet = Tweet.new
    end
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    
    if @tweet.save
      redirect_to root_path, notice: "Tweet was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_back(fallback_location: root_path)
  end

  def home
    @page = params.fetch(:page, 0).to_i
    @pages = (followed_users_ids.count / TWEETS_PER_PAGE.to_f).ceil

    @for_user_tweets = Tweet.tweets_for_me(followed_users_ids).offset(@page * TWEETS_PER_PAGE).limit(TWEETS_PER_PAGE)
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :retweet_id).merge(user: current_user)
    end

    def is_author?
      redirect_back(fallback_location: root_path) unless @tweet.user == current_user
    end

    def followed_users_ids
      ids = [current_user.id]
      current_user.followed_users.each do |user|
        ids.append(user.id)
      end

      return ids
    end
    
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def hashtag_render(content)
     content.gsub(/#\w+/){|word| link_to word, "/tweets?query=#{word.delete('#')}", class: "font-medium"}.html_safe
  end
  
end

app/views/tweets/_alerts.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

app/views/tweets/_form.html.erb
<div class="h-full flex flex-wrap content-center">
  <div class="mx-auto my-auto p-5 bg-gray-50 rounded-md shadow-lg border-2">
    <%= form_with(model: tweet) do |form| %>
      
      <div class="flex justify-between">
        <div class="flex flex-row">
          <div class="flex-none bg-cover bg-center rounded-full h-20 w-20 m-2 transition delay-75 ease-in-out" style="background-image: url(<%= current_user.profile_picture %>)"></div>
          <%= form.label :content, "¿Qué está pasando?", class: "text-4xl mr-20 my-auto w-full" %>
        </div>
        <img src="https://cdn.pixabay.com/photo/2016/12/17/15/50/logo-1913689_1280.png" alt="" class="h-12 w-12 my-auto">
      </div>
      <%= form.text_area :content, class: "mt-5 w-full h-36 border-2 max-h-52 rounded p-2 font-light" %>

      <%= form.hidden_field :retweet_id, value: @tweet.retweet_id %>

      <% if not @tweet.retweet_id.nil? %>
        <%= render '/tweets/retweet', tweet: Tweet.find(@tweet.retweet_id) %>
      <% end %>

      <div class="flex justify-between mt-8">
        <%= form.submit "Crear Tuit", class: "tuiter-button max-w-xs" %>
        <%= link_to 'Regresar', :back, class: "px-5 my-auto hover:bg-gray-800 hover:text-white rounded" %>
      </div>

      <% if tweet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

          <ul>
            <% tweet.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tweets/_more_tweets_buttons.html.erb
<div class="flex justify-around pt-10">
	<% if @page > 0 %>
		<%= link_to url_for(page: @page - 1, query: params[:query]) do %>
			<span class="page-after-button">tweets anteriores</span>
		<% end %>
	<% end %>

	<% if @page >= 1 %>
		<%= link_to url_for(page: 0, query: params[:query]) do %>
			<span class="to-init-button">Al Inicio</span>
		<% end %>
	<% end %> 

	<% if (@page + 1) < @pages %>
		<%= link_to url_for(page: @page + 1, query: params[:query]) do %>
			<span class="page-next-button">mostrar más tweets</span>
		<% end %>
	<% end %>
</div>

app/views/tweets/_retweet.html.erb
<%# tweet card%>
<div class="max-w-3xl border-dashed border-2 rounded-md bg-gray-50 hover:bg-gray-50 mx-auto">
    <%# user details section %>
    <div class="flex space-x-1 p-1">
        <%# image %>
        <div>
            <div class="bg-cover bg-center rounded-full h-10 w-10 m-2 transition delay-75 ease-in-out" style="background-image: url(<%= tweet.user.profile_picture %>)"></div>
        </div>

        <%# account info section %>
        <div class="flex my-auto w-full justify-between">

            <%# account name %>
            <span class="font-light select-none">@<%= tweet.user.account %></span>

            <%# tweet published at %>
            <div class="flex justify-end">
                <%# time published %>
                <span class="text-sm mr-4 font-light my-auto"> 
                    <%= link_to tweet_path(tweet) do %>
                    hace
                    <%= tweet.time_since_publish %>
                    <% end %>
                </span>
            </div>
        </div>
    </div>

    <%# content section %>
    <div class="mx-12 mb-8 font-light select-none">
        <%= tweet.content %>
    </div>
</div>

app/views/tweets/_tweet.html.erb
<%# tweet card%>
<div class="max-w-5xl border-2 bg-white hover:bg-gray-50">
    <%# user details section %>
    <div class="flex p-2">
        <%# image %>
        <div>
            <div class="bg-cover bg-center rounded-full h-12 w-12 m-2 transition delay-75 ease-in-out" style="background-image: url(<%= tweet.user.profile_picture %>)"></div>
        </div>

        <%# account info section %>
        <div class="flex my-auto w-full justify-between">
            
            <div class="inline-block">
                <%# follow unfollow buttons %>
                <span class="text-xs">
                    <% if tweet.user.id != current_user.id %>
                        <% if current_user.followed_users.include?(tweet.user) %>
                            <h5><%= button_to "Siguiendo a", unfollow_path(tweet.user.id), method: "POST", class: "px-2 rounded cursor-pointer transition easy-in-out bg-blue-300 hover:bg-red-300" %></h5>
                        <% else %>
                            <h5><%= button_to "Seguir a", follow_path(tweet.user.id), method: "POST", class: "px-2 rounded cursor-pointer transition easy-in-out hover:bg-blue-300"  %></h5>
                        <% end%>
                    <% end %>
                </span>

                <%# account name %>
                <span class="font-medium select-none">@<%= tweet.user.account %></span>
            </div>

            <%# tweet published at %>
            <div class="flex justify-end">
                <%# time published %>
                <span class="text-sm mr-4 font-light my-auto"> 
                    <%= link_to tweet_path(tweet) do %>
                    hace
                    <%= tweet.time_since_publish %>
                    <% end %>
                </span>

                <%# delete icon if user is author %>
                <span class="my-auto m-2 text-gray-300 hover:text-pink-700">
                    <% if tweet.user.id == current_user.id %>
                        <%= link_to tweet, method: :delete, data: { confirm: '¿estás seguro?' } do %>
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                        <% end %>
                    <% end %>
                </span>
            </div>
        </div>
    </div>

    <%# content section %>
    <div class="mx-12 mb-2 font-light select-none overflow-ellipsis overflow-hidden">
        <%= hashtag_render(tweet.content) %>
    </div>

    <%# retweet section %>
    <% if retweet %>
        <div class="m-2">
            <%= render '/tweets/retweet', tweet: retweet %>
        </div>
    <% end %>

    <%# like unlike retweet section %>
    <div class="flex mt-5 mb-3 justify-around">
        <%# Retweets %>
        <div class="flex space-x-1 my-auto text-gray-400 hover:text-gray-900">
            <%= link_to new_tweet_path(retweet_id: tweet.id) do %>
                <span class="cursor-pointer">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                    </svg>
                </span>
            <% end %>
            
            <span class="text-sm my-auto select-none">
                <%= tweet.retweets.count %> <%= (tweet.retweets.count) == 1 ? 'retweet' : 'retweets'%>
            </span>
        </div>
        
        <%# Likes %>
        <div class="group flex space-x-1 my-auto">
            <span class="cursor-pointer">
                <%= render 'likes/like_buttons', tweet: tweet %>
            </span>
            <span class="text-sm my-auto select-none text-gray-400 group-hover:text-gray-900">
                <%= tweet.likes.count %> <%= (tweet.likes.count) == 1 ? 'Like' : 'Likes'%>
            </span>
        </div>
    </div>
</div>

app/views/tweets/home.html.erb
<div class="flex bg-gray-50 h-14 pl-10 sticky top-0 shadow-sm border-2 bg-opacity-75 backdrop-filter backdrop-blur-sm">
	<span class="my-auto font-semibold text-lg select-none">Inicio</span>
</div>

<div class="mt-3 mx-auto">
  <div class="space-y-1 mb-20">
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>
    
    <% if params[:page].to_i >= 0 %>
      <% (@for_user_tweets.order(created_at: :desc)).each do |tweet| %>
        <%# tweets here %>
        <%= render "/tweets/tweet", tweet: tweet, retweet: Tweet.find_by(id: tweet.retweet_id) %>
      <% end %>

      <%= render 'more_tweets_buttons' %>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="flex flex-row">
	<div class="flex-grow">
		<div class="flex flex-row h-14 bg-white sticky top-0 shadow-sm border-2 justify-between px-5 bg-opacity-75 backdrop-filter backdrop-blur-sm">
			<img src="https://cdn.pixabay.com/photo/2016/12/17/15/50/logo-1913689_1280.png" class="w-7 h-7 my-auto">
			
			<div class="my-auto">
				<%= form_with url: "/tweets", method: :get do |form| %>
					<%= form.text_field :query, class: "border-2 rounded-full px-2 w-96 h-10" %>
					<%= form.submit "Buscar", class: "p-2 px-5 rounded-full hover:bg-gray-300 cursor-pointer" %>
				<% end %>
			</div>

		</div>

		<div class="mt-3 mx-auto">
			<div class="space-y-1 mb-20">
				<p id="notice"><%= notice %></p>
				<p id="alert"><%= alert %></p>
				
				<% if params[:page].to_i >= 0 %>
					<% (@tweets.order(created_at: :desc)).each do |tweet| %>
						<%# tweets here %>
						<%= render "/tweets/tweet", tweet: tweet, retweet: Tweet.find_by(id: tweet.retweet_id) %>
					<% end %>

					<%= render 'more_tweets_buttons' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/tweets/new.html.erb
<%= render 'form', tweet: @tweet %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="max-w-3xl mt-10">
  <div class="space-y-2 mt-2">
    <%= link_to 'Regresar', :back, class: "bg-gray-100 hover:bg-gray-700 hover:text-white px-5 py-1 rounded" %>
    <%= render '/tweets/tweet', tweet: @tweet, retweet: Tweet.find_by(id: @tweet.retweet_id) %>
  </div>

  <% if @tweet.likes.count > 0 %>
    <div class="mt-5 p-5 mx-auto">
      <p class="tuiter-title-md mr-5 text-right">Likes</p>
        <% @tweet.likes.each do |like| %>
          <% user = User.find_by(id: like.user_id) %>
          <div class="flex justify-end">
            <div class="my-auto text-gray-600 font-light select-none text-sm"><%= user.account %></div>
            <div class="shadow-sm border-2 bg-cover bg-center rounded-full h-8 w-8 m-2 transition delay-75 ease-in-out" style="background-image: url(<%= user.profile_picture %>)"></div>
          </div>
        <% end %>
    </div>
  <% end %>
</div>