config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "tweets#home"
  devise_for :users
  
  post '/:id/follow', to: "friends#follow", as: "follow"
  post '/:id/unfollow', to: "friends#unfollow", as: "unfollow"
  
  resources :tweets, except: [:edit, :update] do
    resources :likes, only: [:create, :destroy]
  end
  
  get '/home', to: "tweets#home", as: "home"
  
  get '/api/news', to: "api#news"
  get '/api/:start/:final', to: "api#between_dates"
  get '/api/create', to: "api#create"

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_tweet
    before_action :find_like, only: [:destroy]

    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
        else
            @tweet.likes.create(user_id: current_user.id)
        end

        redirect_back(fallback_location: root_path)
    end

    def destroy
        if not already_liked?
            flash[:notice] = "Cannot unlike"
        else
            @like.destroy
        end

        redirect_back(fallback_location: root_path)
    end

    private
        def already_liked?
            Like.where(user_id: current_user.id, tweet_id: params[:tweet_id]).exists?
        end

        def find_tweet
            @tweet = Tweet.find(params[:tweet_id])
        end

        def find_like
            @like = @tweet.likes.find(params[:id])
        end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_buttons.html.erb
<% pre_like = tweet.likes.find { | like | like.user_id == current_user.id} %>

<% if pre_like %>
    <%= link_to tweet_like_path(tweet, pre_like), method: :delete do%>
        <span class="text-red-600 shadow-lg">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
            </svg>
        </span>
    <% end %>
    
<% else %>
    <%= link_to tweet_likes_path(tweet), method: :post do %>
    <span class="text-gray-400 hover:text-red-600">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
        </svg>
    </span>
    <% end %>
    
<% end %>